apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-job-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-job
  template:
    metadata:
      labels:
        app: ai-job
    spec:
      containers:
      - name: ai-job-container
        image: ai-job
        imagePullPolicy: Never
        # --- NOTICE: NO CPU LIMITS! This is the "bad" one ---